-- Alter users table to add missing columns for user profile management
ALTER TABLE users ADD COLUMN IF NOT EXISTS email_address VARCHAR(255) NULL UNIQUE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS full_name VARCHAR(255) NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS address TEXT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS profile_image VARCHAR(255) NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS phone VARCHAR(15) NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS phone_verified TINYINT DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS email_verified TINYINT DEFAULT 0;
